DROP TABLE IF EXISTS genders CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS auth CASCADE;

-- ê´ï ÉeÅ[ÉuÉã
CREATE TABLE genders (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(1) NOT NULL
);

CREATE TABLE users (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	handle VARCHAR(100),
	gender INTEGER NULL,
	email VARCHAR(100) NOT NULL UNIQUE 
);

CREATE TABLE auth (
	id SERIAL NOT NULL PRIMARY KEY,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL UNIQUE,
	handler VARCHAR(100) NOT NULL
);